<section class="section--first" id="blog">
            <article class="first--article">
    <?php foreach($articles as $article): ?>
        <?php
            $url = $blogManager->getUrlByImageId($article['image_id']);
            $alt = $blogManager->getAltByImageId($article['image_id']);
        ?>
                <div class="news">
                    <ul class="cards__ul">
                    <h1><?= $article['title'];?></h1>   
                        <li class="cards_li"><?= $article['timestamp'];?></li>
                        <li class="cards_li"><?= $article['content'];?></li>
                    </ul>
                </div>

    <?php endforeach; ?>  
            </article> 
<?php require './assets/views/includes/_aside.phtml'; ?>
</section>