<section class="section--first" id="section--work">
    <?php require './assets/views/includes/_aside.phtml'; ?>
    <article class="first--article">
        <div>
            <h3><?= $articles[0]['title'];?></h3>
            <ul class="cards__ul">
                <li class="cards_li"><?= $articles[0]['content'];?></li>
                <li class="cards_li"><?= $articles[0]['timestamp'];?></li>
            </ul>
            <div class="footer--cards">
                <a href="/alexisbeucher/works/<?= $articles[0]['id'];?>" class="underline">Découvrir le projet</a>
            </div>
        </div>    
    </article>
</section>