<section class="section--first" id="contact">
    <?php require './assets/views/includes/_aside.phtml'; ?>
    <article class="first--article">
        <div class="formulaire">
            <form action="/alexisbeucher/postcontact" method="post" enctype="multipart/form-data">
                <fieldset>
                    <legend>vos coordonnées</legend>
                    <div class="field">
                        <label for="inputName">Votre nom</label>
                        <div class="value">
                            <input type="text" name="name" id="inputName" required>
                        </div>
                    </div>
                    <div class="field">
                        <label for="inputEmail">Email</label>
                        <div class="value">
                            <input type="text" name="email" id="inputEmail" required>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                        <legend>Votre message</legend>
                        <textarea name="message" id="query" required ></textarea>
                </fieldset>
                <div class="toolbar">
                    <button type="submit" class="button-47 underline">Envoyer</button>
                </div>
            </form>
        </div>
    </article>
</section>