<section class="section--first">
    <!-- <?php require './assets/views/includes/_aside.phtml'; ?> -->
    <article class="first--article">
        <h1>Bienvenue sur mon portfolio</h1>
        <p>Après 5 années de CDI & missions d'intérims j'ai décidé de devenir développeur web, 
            je suis quelqu'un de très motivé consacrant mon temps personnel pour peaufiner mes compétences.
            Je suis actuellement en <b>recherche d'un stage & d'une alternance</b> dans ce domaine</p>
        <a href="/alexisbeucher/works" class="links underline">Voir mes projets</a>
    </article>
</section>