<section class="section--first">
    <article class="first--article">
        <h1>Bienvenue sur mon portfolio</h1>
        <p>Passionné de l'univers web en  général et des technologies de développement web,
             je me renseigne sur les technologies du web à travers les documentations et le
              contenu en ligne. Je ne m'arrête pas en cas de problème et j'utilise ma curiosité 
              pour avancer.</p>
        <a href="/alexisbeucher/works" class="links underline">Voir mes projets</a>
    </article>
    
</section>