<!doctype html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/alexisbeucher/assets/public/css/style.css">
<title><?= $pageName ?></title>
</head>
<body>
    <?php require './assets/views/includes/_header.phtml'; ?>
    <main class="container">
        <?php require './assets/views/'.$page.'.phtml'; ?>
    </div>
    <script src="https://kit.fontawesome.com/09a639c3b1.js" crossorigin="anonymous"></script>
</body>
</html>