<section class="section--first">
    <article class="first--article">
        <form action="/AlexisBeucher/logincheck" method="post">
            <fieldset>
            <legend>Se connecter</legend>
            <div class="field">
                <label for="username">Nom d'utilisateur</label>
                <div class="value">
                    <input type="text" name="username">
                </div>
            </div>
            <div class="field">
                <label for="password">Mot de passe</label>
                <div class="value">
                    <input type="password" name="password">
                </div>
            </div>
                </fieldset>
            <div class="toolbar">
                <button type="submit" class="button-4">Se connecter</button>
            </div>
        </form>
    </article>
</section>
