<section class="section--first" id="section--work">
    <article class="first--article works">
    <?php foreach($allWorks as $works): ?>
        <div class="cards belleepoque">
            <div class="footer--cards">
                <a href="/alexisbeucher/works/<?= $works['id'];?>" class="underline">Voir plus</a>
                <a href="<?= $works['website'];?>" class="underline">Visiter</a>
            </div>
        </div>
    <?php endforeach; ?>
    </article>
</section>
