<div id="works_show">
    <section class="section--first">
        <article class="first--article aside">
            
                <ul class="cards__ul">
                    <span class="work-details">Languages <li class="cards_li"><?= $work[0]['languages'];?></li></span>
                    <span class="work-details">Catégorie <li class="cards_li"><?= $work[0]['category_id'];?></li></span>
                    <span class="work-details">Description <li class="cards_li"><?= $work[0]['description'];?></li></span>
                </ul>
        </article>
        <div class="tabs">
      <div
        role="tablist"
        aria-label="tabs component"
        class="tabs-btn-container"
      >
        <button
          role="tab"
          aria-controls="panel-1"
          id="tab-1"
          type="button"
          aria-selected="true"
          tabindex="0"
          class="tab active-tab underline"
        >
          Présentation
        </button>
        <button
          role="tab"
          aria-controls="panel-2"
          id="tab-2"
          type="button"
          aria-selected="false"
          tabindex="-1"
          class="tab underline"
        >
          La réalisation du site
        </button>
        <button
          role="tab"
          aria-controls="panel-3"
          id="tab-3"
          type="button"
          aria-selected="false"
          tabindex="-1"
          class="tab underline"
        >
          Informations 
        </button>
      </div>
      <div
        id="panel-1"
        role="tabpanel"
        tabindex="0"
        aria-labelledby="tab-1"
        class="tab-content active-tab-content"
      >
        <p>
        <?= $work[0]['description'];?>
        </p>
      </div>

      <div
        id="panel-2"
        role="tabpanel"
        tabindex="0"
        aria-labelledby="tab-2"
        class="tab-content"
      >
        <p>
        <?= $work[0]['description'];?>
        </p>
      </div>

      <div
        id="panel-3"
        role="tabpanel"
        tabindex="0"
        aria-labelledby="tab-3"
        class="tab-content"
      >
        <p>
            <?= $work[0]['description'];?>
        </p>
      </div>
    </div>

        <!-- <article class="first--article second--article">
        <h1><?= $work[0]['name'];?></h1>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Earum voluptatibus mollitia velit cupiditate aliquid. 
                Qui necessitatibus unde, quas fugit consequuntur, sint, ipsa perferendis quasi neque iusto temporibus quod dicta 
                eaque dolorem eveniet libero velit. Molestias nam saepe officiis cum distinctio perspiciatis nobis obcaecati 
                doloremque possimus ut dolor consequuntur magnam id, voluptas ad placeat reiciendis aut eos minima? Tempora, 
                amet error ducimus debitis aspernatur ipsum aperiam quaerat neque inventore, ea aut accusantium pariatur saepe 
                vitae cumque! Est natus magni architecto corporis! Quos necessitatibus, sed aperiam pariatur esse porro autem 
                dolorem, error nesciunt, quasi dicta minus qui. Dolore exercitationem deleniti eum debitis.</p>
            <a href="/alexisbeucher/works/<?= $work[0]['website'];?>" class="links underline">Visiter le site</a>
            <nav>
                <a href="#page-2"><i class="fa-solid fa-arrow-down fa-2xl"></i></a>
            </nav>
            </article> -->
        
    </section>
    <!-- <section class="section--second" id="page-2">
        <article class="workscreen grayscale">
                <img src="/alexisbeucher/assets/public/images/belleepoque-lessons.webp" 
                alt="Capture d'écran du site belle epoque"
                width="60%">
        </article>
    </section> -->
</div>