<header>
    <nav>
        <h1 class="logo">Alexis Beucher</h1>
        <ul class="header__nav__ul">
            <li class="header__nav__li"><a href="/alexisbeucher/">Home</a></li>
            <li class="header__nav__li"><a href="/alexisbeucher/works">Works</a></li>
            <li class="header__nav__li"><a href="/alexisbeucher/blog">Blog</a></li>
            <li class="header__nav__li"><a href="/alexisbeucher/contact">Contact</a></li>
        </ul>
        <span></span>
    </nav>
</header>