<header>
    <nav class="nav__header">
        <h1 class="logo">Alexis Beucher</h1>
        <ul class="header__nav__ul">
            <li class="header__nav__li"><a href="/alexisbeucher/">Home</a></li>
            <li class="header__nav__li"><a href="/alexisbeucher/admin">Dashboard</a></li>
            <li class="header__nav__li"><a href="/alexisbeucher/admin/works">Works</a></li>
            <li class="header__nav__li"><a href="/alexisbeucher/admin/blog">Blog</a></li>
        </ul>
        <span class="burger"></span>
    </nav>
</header>