<h1>This is a admin works creating page</h1>
<form action="/admin/addworks" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Ajouter un projet</legend>
        <div class="field">
            <label for="name">Nom</label>
            <div class="value">
                <input type="text" name="name">
            </div>
        </div>
        <div class="field">
            <label for="customer">customer</label>
            <div class="value">
                <input type="text" name="customer">
            </div>
            </div>
        <div class="field">
            <label for="languages">Languages</label>
            <div class="value">
                <input type="text" name="languages">
            </div>
        </div>
        
        <div class="field">
            <label for="website">Website</label>
            <div class="value">
                <input type="text" name="website">
            </div>
        </div>
        <div class="field">
            <label for="category_id">Categorie</label>
            <select id="category_id" name="category_id">
                <option value="1">FullStack</option>
                <option value="2">Front End</option>
                <option value="3">Back End</option>
            </select>
        </div>
        <div class="field">
        <label for="description">Description</label>
            <div class="value">
                <input type="text" name="description">
            </div>
        </div>
    </fieldset>
    <div class="toolbar">
        <button type="submit">Importer le cours</button>
    </div>
</form>