<?php
  foreach($allWorks as $works):
?>
    <div class="cards">
        <h3><?= $works['name'];?></h3>
        <ul class="cards__ul">
            <li class="cards_li"><?= $works['customer'];?></li>
            <li class="cards_li"><?= $works['languages'];?></li>
            <li class="cards_li"><a href="<?= $works['website'];?>"><?= $works['website'];?></a></li>
            <li class="cards_li"><?= $works['category_id'];?></li>
        </ul>
        <button class="cards__button"><a href="/alexisbeucher/works/<?= $works['id'];?>">Découvrir le projet</a> </button>
    </div>
<?php endforeach; ?>