<aside>
    <?php require './assets/views/includes/_lastnews.phtml'; ?>
    <?php require './assets/views/includes/_lastworks.phtml'; ?>
    <h2>Contact</h2>
    
    <ul class="contact--ul">
        <li class="contact--li"><i class="fa-solid fa-location-dot"></i>Rennes</li>
        <li class="contact--li"><i class="fa-solid fa-envelope"></i></i>Alexis.beucher01@gmail.com</li>
        <li class="contact--li"><i class="fa-brands fa-linkedin"></i><a href="https://www.linkedin.com/in/alexis-beucher01/" class="underline">LinkedIn</a></li>
        <li class="contact--li"><i class="fa-brands fa-github"></i><a href="https://github.com/alexisbchr" class="underline">Github</a></li>
        <li class="contact--li"><i class="fa-solid fa-check"></i>Disponible pour alternance</li>
    </ul>
</aside>