<header>
    <nav class="nav__header">
        <h1 class="logo">Alexis Beucher</h1>
        <ul class="header__nav__ul" id="modalBurger">
            <li class="header__nav__li underline"><a href="/">Home</a></li>
            <li class="header__nav__li underline"><a href="/works">Works</a></li>
            <li class="header__nav__li underline"><a href="/blog">Blog</a></li>
            <li class="header__nav__li underline"><a href="/contact">Contact</a></li>
        </ul>
        <div class="burger" id="openBurger">
        <span></span>
        </div>
    </nav>
</header>