<div id="admin">
    <section class="section--first">
        <article class="first--article">
            <form action="/alexisbeucher/admin/addworks" method="post" enctype="multipart/form-data">
                <fieldset>
                    <legend>Ajouter un projet</legend>
                    <div class="field">
                        <label for="name">Nom</label>
                        <div class="value">
                            <input type="text" name="name">
                        </div>
                    </div>
                    <div class="field">
                        <label for="customer">Client</label>
                        <div class="value">
                            <input type="text" name="customer">
                        </div>
                        </div>
                    <div class="field">
                        <label for="languages">Languages</label>
                        <div class="value">
                            <input type="text" name="languages">
                        </div>
                    </div>
                    
                    <div class="field">
                        <label for="website">Website</label>
                        <div class="value">
                            <input type="text" name="website">
                        </div>
                    </div>
                    <div class="field">
                        <label for="category_id">Categorie</label>
                        <select id="category_id" name="category_id">
                            <option value="1">FullStack</option>
                            <option value="2">Front End</option>
                            <option value="3">Back End</option>
                        </select>
                    </div>
                    <div class="field">
                    <label for="description">Description</label>
                        <div class="value">
                            <input type="text" name="description">
                        </div>
                    </div>
                    <div class="field">
                        <label for="image">Choisir une photo</label>
                        <div class="value">
                            <input type="file" accept="image/png, image/jpeg, image/webp" name="image">
                        </div>
                    </div>
                    <div class="field">
                    <label for="alt">alt</label>
                        <div class="value">
                            <input type="text" name="alt">
                        </div>
                    </div>
                </fieldset>
                <fieldset class="complements">
                    <legend>Informations complémentaires</legend>
                    <div class="field">
                        <label for="realisation">Réalisation du site</label>
                        <div class="value">
                            <textarea type="textarea" name="realisation"></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <label for="information">Informations</label>
                        <textarea type="textarea" name="information"></textarea>
                        <div class="value">
                        
                        </div>
                    </div>
                </fieldset>
                <div class="toolbar">
                    <button type="submit">Importer le cours</button>
                </div>
            </form>
        </article>
    </section>  
</div>
