<div id="admin">
    <section class="section--first"  id="admin">
        <article class="first--article">        
            <form action="/admin/editworks/<?= $work[0]['id']?>" method="post" enctype="multipart/form-data">
                <fieldset>
                    <legend>Modifier un projet</legend>
                    <div class="field">
                        <label for="name">Nom</label>
                        <div class="value">
                            <input type="hidden" name="id" value="<?= $work[0]['id'] ?>">
                            <input type="text" name="name" value="<?= $work[0]['name']?>">
                        </div>
                    </div>
                    <div class="field">
                        <label for="customer">customer</label>
                        <div class="value">
                            <input type="text" name="customer" value="<?= $work[0]['customer']?>">
                        </div>
                        </div>
                    <div class="field">
                        <label for="languages">Languages</label>
                        <div class="value">
                            <input type="text" name="languages" value="<?= $work[0]['languages']?>">
                        </div>
                    </div>
                    
                    <div class="field">
                        <label for="website">Website</label>
                        <div class="value">
                            <input type="text" name="website" value="<?= $work[0]['website']?>">
                        </div>
                    </div>
                    <div class="field">
                        <label for="category_id">Categorie</label>
                        <select id="category_id" name="category_id" value="<?= $work[0]['category_id']?>">
                            <option value="1">FullStack</option>
                            <option value="2">Front End</option>
                            <option value="3">Back End</option>
                        </select>
                    </div>
                    <div class="field">
                    <label for="description">Description</label>
                        <div class="value">
                            <input type="text" name="description" value="<?= $work[0]['description']?>">
                        </div>
                    </div>
                </fieldset>
                <fieldset class="complements">
                    <legend>Informations complémentaires</legend>
                    <div class="field">
                        <label for="realisation">Réalisation du site</label>
                        <div class="value">
                            <textarea type="textarea" name="realisation" value="<?= $work[0]['realisation']?>"></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <label for="information">Informations</label>
                        
                        <div class="value">
                        <textarea type="textarea" name="information" value="<?= $work[0]['information']?>"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="toolbar">
                    <button type="submit">Importer le cours</button>
                </div>
            </form>
        </article>
    </section>
</div>