<section class="section--first" id="admin">
    <article class="first--article">
        <ul>
            <li><a href="admin/addworks">Ajouter un projet</a></li>
            <li><a href="admin/works">Voir tous les projets</a></li>
        </ul>
    </article>
    <article class="first--article">
        <ul>
            <li><a href="admin/addarticles">Ajouter un articles</a></li>
            <li><a href="admin/blog">Voir tous les articles</a></li>
        </ul>
    </article>
</section>
