<!doctype html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="/alexisbeucher/assets/public/css/style.css">
<script src="https://cdn.tiny.cloud/1/hz4dws2iqe38ifsapqauj04llnh9g0cny4wkp31nzmbdiodw/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<title><?= $pageName ?></title>
</head>
<body>
    <?php require './assets/views/includes/_adm-header.phtml'; ?>
    <main class="container">
        <?php require './assets/views/admin/'.$page.'.phtml'; ?>
    </main>
    <script src="/alexisbeucher/assets/public/js/index.js"></script>
</body>
</html>