<section class="section--first" id="section--work">
    <article class="first--article">
        <div>
            <h3><?= $articles[0]['title'];?></h3>
            <ul class="cards__ul">
                <li class="cards_li"><?= $articles[0]['content'];?></li>
                <li class="cards_li"><?= $articles[0]['timestamp'];?></li>
            </ul>
            <div class="footer--cards">
                <a href="/alexisbeucher/admin/blog/<?= $articles[0]['id'];?>" class="underline">Découvrir l'article</a>
                <a href="/alexisbeucher/admin/editarticles/<?= $articles[0]['id'];?>" class="underline">Editer l'article</a>
            </div>
        </div>    
    </article>
</section>