<section class="section--first" id="section--work">
    <article class="first--article works">
    <?php foreach($allWorks as $works): ?>
        <div class="cards belleepoque">
            <div class="footer--cards">
                <a href="/alexisbeucher/admin/works/<?= $works['id'];?>" class="underline">Voir plus</a>
                <a href="/alexisbeucher/admin/editworks/<?= $works['id'];?>" class="underline">Modifier le projet</a>
                <a href="/alexisbeucher/admin/deleteworks/<?= $works['id'];?>" class="underline">Supprimer le projet</a>
            </div>
        </div>
    <?php endforeach; ?>
    </article>
</section>