<div id="admin">
    <section class="section--first">
        <article class="first--article works">
        <?php foreach($allWorks as $works): ?>
            <?php
                $url = $worksManager->getUrlByImageId($works['image_id']);
            ?>
            <div class="cards ">
                <img src="<?= $url; ?>" alt="ezezeze" width="100%">
                <div class="footer--cards">
                    <a href="/admin/works/<?= $works['id'];?>" 
                    class="underline">Voir plus</a>
                    <a href="/admin/editworks/<?= $works['id'];?>" 
                    class="underline">Modifier le projet</a>
                    <a href="/admin/deleteworks/<?= $works['id'];?>" 
                    class="underline">Supprimer le projet</a>
                </div>
            </div>
        <?php endforeach; ?>
        </article>
    </section>    
</div>
